//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograAvanzada2023.Models2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_PROYECTO_PAEntities : DbContext
    {
        public DB_PROYECTO_PAEntities()
            : base("name=DB_PROYECTO_PAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAB_CATEGORIAS> TAB_CATEGORIAS { get; set; }
        public virtual DbSet<TAB_CURSOS> TAB_CURSOS { get; set; }
        public virtual DbSet<TAB_ESTADO> TAB_ESTADO { get; set; }
        public virtual DbSet<TAB_INGREDIENTES> TAB_INGREDIENTES { get; set; }
        public virtual DbSet<TAB_INSTRUCCIONES> TAB_INSTRUCCIONES { get; set; }
        public virtual DbSet<TAB_PROFESOR> TAB_PROFESOR { get; set; }
        public virtual DbSet<TAB_RECETAS> TAB_RECETAS { get; set; }
        public virtual DbSet<TAB_ROL> TAB_ROL { get; set; }
        public virtual DbSet<TAB_TAGS> TAB_TAGS { get; set; }
        public virtual DbSet<TAB_USER> TAB_USER { get; set; }
    }
}
