//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograAvanzada2023.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_USER()
        {
            this.TAB_CURSOS = new HashSet<TAB_CURSOS>();
            this.TAB_RECETAS = new HashSet<TAB_RECETAS>();
        }
    
        public int ID_USER { get; set; }
        public string NOMBRE_USER { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public Nullable<System.DateTime> FECHA_CONEXION { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_CURSOS> TAB_CURSOS { get; set; }
        public virtual TAB_ESTADO TAB_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_RECETAS> TAB_RECETAS { get; set; }
        public virtual TAB_ROL TAB_ROL { get; set; }
    }
}
