//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograAvanzada2023.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_TAGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_TAGS()
        {
            this.TAB_RECETAS = new HashSet<TAB_RECETAS>();
        }
    
        public int ID_TAGS { get; set; }
        public string TAGS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_RECETAS> TAB_RECETAS { get; set; }
    }
}
