//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograAvanzada2023.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_INSTRUCCIONES
    {
        public int ID_INSTRUCCIONES { get; set; }
        public Nullable<int> COD_RECETA { get; set; }
        public string INSTRUCCIONES { get; set; }
    
        public virtual TAB_RECETAS TAB_RECETAS { get; set; }
    }
}
