CREATE DATABASE DB_PROYECTO_PA;
USE DB_PROYECTO_PA;

drop database DB_PROYECTO_PA;

-- Creación de la tabla de estados
CREATE TABLE TAB_ESTADO (
    ID_ESTADO INT PRIMARY KEY IDENTITY(1,1),
    ESTADO VARCHAR(255)
);

-- Creación de la tabla de roles
CREATE TABLE TAB_ROL (
    ID_ROL INT PRIMARY KEY IDENTITY(1,1),
    ROL VARCHAR(255)
);

-- Creación de la tabla de categorías
CREATE TABLE TAB_CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY IDENTITY(1,1),
    CATEGORIA VARCHAR(255)
);

-- Creación de la tabla de etiquetas (tags)
CREATE TABLE TAB_TAGS (
    ID_TAGS INT PRIMARY KEY IDENTITY(1,1),
    TAGS VARCHAR(255)
);

-- Creación de la tabla de profesores
CREATE TABLE TAB_PROFESOR (
    ID_PROFESOR INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(255),
    APELLIDO_MAT VARCHAR(255),
    APELLIDO_PAT VARCHAR(255),
    CEDULA VARCHAR(255),
    ID_ROL INT FOREIGN KEY REFERENCES TAB_ROL(ID_ROL) 
);

-- Creación de la tabla de usuarios
CREATE TABLE TAB_USER (
    ID_USER INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_USER VARCHAR(255),
    PASSWORD VARCHAR(255),
    ID_ROL INT FOREIGN KEY REFERENCES TAB_ROL(ID_ROL),
    FECHA_CONEXION DATE,
    ID_ESTADO INT FOREIGN KEY REFERENCES TAB_ESTADO(ID_ESTADO)
);

-- Creación de la tabla de recetas
CREATE TABLE TAB_RECETAS (
    COD_RECETA INT PRIMARY KEY IDENTITY(1,1),
    NOM_RECETA VARCHAR(255),
    ID_CATEGORIA INT FOREIGN KEY REFERENCES TAB_CATEGORIAS(ID_CATEGORIA),
    DURACION VARCHAR(255),
    PORCIONES VARCHAR(255),
    ID_TAGS INT FOREIGN KEY REFERENCES TAB_TAGS (ID_TAGS),
    ID_ESTADO INT FOREIGN KEY REFERENCES TAB_ESTADO(ID_ESTADO),
    ID_USER INT FOREIGN KEY REFERENCES TAB_USER(ID_USER),
    FECHA_CREACION DATE,
    FECHA_MODIFICACION DATE
);

-- Creación de la tabla de cursos
CREATE TABLE TAB_CURSOS (
    CODIGO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(255),
    ID_PROFESOR INT FOREIGN KEY REFERENCES TAB_PROFESOR(ID_PROFESOR),
    HORARIO VARCHAR(255),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    COD_RECETA INT FOREIGN KEY REFERENCES TAB_RECETAS(COD_RECETA), 
    ID_USER INT FOREIGN KEY REFERENCES TAB_USER(ID_USER), 
    ID_ESTADO INT FOREIGN KEY REFERENCES TAB_ESTADO(ID_ESTADO)
);

-- Creación de la tabla de ingredientes
CREATE TABLE TAB_INGREDIENTES (
    ID_INGREDIENTES INT PRIMARY KEY IDENTITY(1,1),
    COD_RECETA INT FOREIGN KEY REFERENCES TAB_RECETAS(COD_RECETA),
    INGREDIENTES VARCHAR(255)
);

-- Creación de la tabla de instrucciones
CREATE TABLE TAB_INSTRUCCIONES (
    ID_INSTRUCCIONES INT PRIMARY KEY IDENTITY(1,1),
    COD_RECETA INT FOREIGN KEY REFERENCES TAB_RECETAS(COD_RECETA),
    INSTRUCCIONES TEXT
);


-- Inserciones para TAB_ESTADO
SELECT * FROM TAB_ESTADO;
INSERT INTO TAB_ESTADO (ESTADO) VALUES ('Activo');
INSERT INTO TAB_ESTADO (ESTADO) VALUES ('Inactivo');

-- Inserciones para TAB_ROL
SELECT * FROM TAB_ROL;
INSERT INTO TAB_ROL (ROL) VALUES ('admin');
INSERT INTO TAB_ROL (ROL) VALUES ('usuario');

-- Inserciones para TAB_CATEGORIAS
SELECT * FROM TAB_CATEGORIAS;
INSERT INTO TAB_CATEGORIAS (CATEGORIA) VALUES ('Desayuno');
INSERT INTO TAB_CATEGORIAS (CATEGORIA) VALUES ('Almuerzo');
INSERT INTO TAB_CATEGORIAS (CATEGORIA) VALUES ('Cena');


-- Inserciones para TAB_TAGS
SELECT * FROM TAB_TAGS;
INSERT INTO TAB_TAGS (TAGS) VALUES ('Asiatica');
INSERT INTO TAB_TAGS (TAGS) VALUES ('Americana');
INSERT INTO TAB_TAGS (TAGS) VALUES ('Europea');

-- Inserciones para TAB_PROFESOR
SELECT * FROM TAB_PROFESOR;
INSERT INTO TAB_PROFESOR (NOMBRE, APELLIDO_MAT, APELLIDO_PAT, CEDULA, ID_ROL) 
VALUES ('Juan', 'Perez', 'Lopez', '123456789', 1);
INSERT INTO TAB_PROFESOR (NOMBRE, APELLIDO_MAT, APELLIDO_PAT, CEDULA, ID_ROL) 
VALUES ('Adrian', 'Peraza', 'Baldizon', '123456789', 2);

-- Inserciones para TAB_USER
SELECT * FROM TAB_USER;
INSERT INTO TAB_USER (NOMBRE_USER, PASSWORD, ID_ROL, FECHA_CONEXION, ID_ESTADO) 
VALUES ('Ruben', 'Hola1234', 1, '2023-01-01', 1);

-- Inserciones para TAB_RECETAS
SELECT * FROM TAB_RECETAS;
INSERT INTO TAB_RECETAS (NOM_RECETA, ID_CATEGORIA, DURACION, PORCIONES, ID_TAGS, ID_ESTADO, ID_USER, FECHA_CREACION, FECHA_MODIFICACION) 
VALUES ('Panqueques', 1, '20 minutos', '4', 1, 1, 1, '2023-01-01', '2023-01-01');
INSERT INTO TAB_RECETAS (NOM_RECETA, ID_CATEGORIA, DURACION, PORCIONES, ID_TAGS, ID_ESTADO, ID_USER, FECHA_CREACION, FECHA_MODIFICACION) 
VALUES ('Ensalada César', 2, '15 minutos', '2', 2, 1, 1, '2023-01-02', '2023-01-02');
INSERT INTO TAB_RECETAS (NOM_RECETA, ID_CATEGORIA, DURACION, PORCIONES, ID_TAGS, ID_ESTADO, ID_USER, FECHA_CREACION, FECHA_MODIFICACION) 
VALUES ('Lasagna', 3, '45 minutos', '6', 3, 1, 1, '2023-01-03', '2023-01-03');

-- Inserciones para TAB_CURSOS
SELECT * FROM TAB_CURSOS;
INSERT INTO TAB_CURSOS (NOMBRE, ID_PROFESOR, HORARIO, FECHA_INICIO, FECHA_FIN, COD_RECETA, ID_USER, ID_ESTADO) 
VALUES ('Cocina Italiana Básica', 1, 'Lunes y Miércoles 10:00-12:00', '2023-02-01', '2023-06-01', 1, 1, 1);
INSERT INTO TAB_CURSOS (NOMBRE, ID_PROFESOR, HORARIO, FECHA_INICIO, FECHA_FIN, COD_RECETA, ID_USER, ID_ESTADO) 
VALUES ('Repostería Avanzada', 2, 'Martes y Jueves 15:00-17:00', '2023-02-02', '2023-06-02', 2, 1, 2);
INSERT INTO TAB_CURSOS (NOMBRE, ID_PROFESOR, HORARIO, FECHA_INICIO, FECHA_FIN, COD_RECETA, ID_USER, ID_ESTADO) 
VALUES ('Cocina Mexicana Contemporánea', 1, 'Viernes 18:00-21:00', '2023-02-03', '2023-06-03', 3, 1, 1);

-- Inserciones para TAB_INGREDIENTES
SELECT * FROM TAB_INGREDIENTES;
INSERT INTO TAB_INGREDIENTES (COD_RECETA, INGREDIENTES) VALUES (1, 'Harina');
INSERT INTO TAB_INGREDIENTES (COD_RECETA, INGREDIENTES) VALUES (3, 'Leche');
INSERT INTO TAB_INGREDIENTES (COD_RECETA, INGREDIENTES) VALUES (2, 'Huevos');

-- Inserciones para TAB_INSTRUCCIONES
SELECT * FROM TAB_INSTRUCCIONES;
INSERT INTO TAB_INSTRUCCIONES (COD_RECETA, INSTRUCCIONES) VALUES (3, 'Mezclar la harina y los huevos');
INSERT INTO TAB_INSTRUCCIONES (COD_RECETA, INSTRUCCIONES) VALUES (1, 'Añadir leche y mezclar hasta obtener una masa homogénea');
INSERT INTO TAB_INSTRUCCIONES (COD_RECETA, INSTRUCCIONES) VALUES (2, 'Verter en la sartén y cocinar por ambos lados');
