//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PrograAvanzada.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_CURSOS
    {
        public int CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ID_PROFESOR { get; set; }
        public string HORARIO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<int> COD_RECETA { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
    
        public virtual TAB_RECETAS TAB_RECETAS { get; set; }
        public virtual TAB_ESTADO TAB_ESTADO { get; set; }
        public virtual TAB_PROFESOR TAB_PROFESOR { get; set; }
        public virtual TAB_USER TAB_USER { get; set; }
    }
}
