//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PrograAvanzada.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_CATEGORIAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_CATEGORIAS()
        {
            this.TAB_RECETAS = new HashSet<TAB_RECETAS>();
        }
    
        public int ID_CATEGORIA { get; set; }
        public string CATEGORIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_RECETAS> TAB_RECETAS { get; set; }
    }
}
