//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PrograAvanzada.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_RECETAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_RECETAS()
        {
            this.TAB_CURSOS = new HashSet<TAB_CURSOS>();
            this.TAB_INGREDIENTES = new HashSet<TAB_INGREDIENTES>();
            this.TAB_INSTRUCCIONES = new HashSet<TAB_INSTRUCCIONES>();
        }
    
        public int COD_RECETA { get; set; }
        public string NOM_RECETA { get; set; }
        public Nullable<int> ID_CATEGORIA { get; set; }
        public string DURACION { get; set; }
        public string PORCIONES { get; set; }
        public Nullable<int> ID_TAGS { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual TAB_CATEGORIAS TAB_CATEGORIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_CURSOS> TAB_CURSOS { get; set; }
        public virtual TAB_ESTADO TAB_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_INGREDIENTES> TAB_INGREDIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_INSTRUCCIONES> TAB_INSTRUCCIONES { get; set; }
        public virtual TAB_TAGS TAB_TAGS { get; set; }
        public virtual TAB_USER TAB_USER { get; set; }
    }
}
